/run/initialize

/vis/open OGL
/vis/viewer/set/autoRefresh true
/vis/drawVolume

/vis/viewer/set/viewpointThetaPhi 120 170 deg

/vis/viewer/set/style wireframe
/vis/viewer/refresh

/vis/viewer/set/auxiliaryEdge true

/gun/particle e-
/gun/energy 10 GeV

# Particle filter: hide gammas and neutrons
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/scene/notifyHandlers scene-0
/vis/filtering/trajectories/particleFilter-0/add neutron
/vis/scene/notifyHandlers scene-0
/vis/filtering/trajectories/particleFilter-0/invert true
/vis/scene/notifyHandlers scene-0


/vis/modeling/trajectories/create/generic
/vis/modeling/trajectories/generic-0/default/setDrawStepPts false
/vis/scene/notifyHandlers scene-0

/vis/scene/add/trajectories smooth

/vis/modeling/trajectories/create/drawByCharge

/vis/modeling/trajectories/drawByCharge-0/set -1 red

/vis/modeling/trajectories/drawByCharge-0/set +1 blue

/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts false

/vis/scene/add/trajectories drawByCharge-0

/run/beamOn 1

/vis/ogl/export electron.eps


